# Ce fichier est le point d'entrée pour configurer vos propres services.
# Les fichiers dans le sous-répertoire packages/ configurent vos dépendances.

parameters:

services:
    # Configuration par défaut pour les services dans *ce* fichier
    _defaults:
        autowire: true # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés aux événements, etc.

    # Configuration pour App\Service\Pagination

    App\Service\Pagination:
        arguments:
            $security: '@security.token_storage'

    # Rend les classes dans src/ disponibles comme services
    # Cela crée un service par classe dont l'ID est le nom de la classe entièrement qualifiée
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
            
    # Ajoutez plus de définitions de services si nécessaire
    # Remarque : les dernières définitions remplacent les précédentes
